export const APP_ACTIONS = {
  GET_FEATURE_TOGGLES: 'GET_FEATURE_TOGGLES',
  GET_FEATURE_TOGGLES_RESOLVING: 'GET_FEATURE_TOGGLES_RESOLVING',
  GET_FEATURE_TOGGLES_RESOLVED: 'GET_FEATURE_TOGGLES_RESOLVED',
  GET_FEATURE_TOGGLES_ERROR: 'GET_FEATURE_TOGGLES_ERROR',
  GET_FEATURE_TOGGLES_EMPTY: 'GET_FEATURE_TOGGLES_EMPTY',

  // reducer actions
  UPDATE_BRANDBAR_SUBTITLE: 'UPDATE_BRANDBAR_SUBTITLE',
  UPDATE_DATA_SET: 'UPDATE_DATA_SET',

  // TODO: should be removed once we remove the splash screen
  SHOW_SPLASH_SCREEN: 'SHOW_SPLASH_SCREEN'
};
