export const PROFILER_ACTIONS = {
  // fetch details(like default) for a context id
  GET_CONTEXT: 'GET_CONTEXT',
  GET_CONTEXT_RESOLVED: 'GET_CONTEXT_RESOLVED',
  GET_CONTEXT_RESOLVING: 'GET_CONTEXT_RESOLVING',
  GET_CONTEXT_ERROR: 'GET_CONTEXT_ERROR',

  GET_DATASET_METADATA: 'GET_DATASET_METADATA',
  GET_DATASET_METADATA_RESOLVED: 'GET_DATASET_METADATA_RESOLVED',
  GET_DATASET_METADATA_RESOLVING: 'GET_DATASET_METADATA_RESOLVING',
  GET_DATASET_METADATA_ERROR: 'GET_DATASET_METADATA_ERROR',

  GET_INNOVATION_ITEMS: 'GET_INNOVATION_ITEMS',
  GET_INNOVATION_ITEMS_RESOLVING: 'GET_INNOVATION_ITEMS_RESOLVING',
  GET_INNOVATION_ITEMS_RESOLVED: 'GET_INNOVATION_ITEMS_RESOLVED',
  GET_INNOVATION_ITEMS_ERROR: 'GET_INNOVATION_ITEMS_ERROR',

  GET_MARKET_SHARE: 'GET_MARKET_SHARE',
  GET_MARKET_SHARE_RESET_TO_INITIAL: 'GET_MARKET_SHARE_RESET_TO_INITIAL',
  GET_MARKET_SHARE_RESOLVING: 'GET_MARKET_SHARE_RESOLVING',
  GET_MARKET_SHARE_RESOLVED: 'GET_MARKET_SHARE_RESOLVED',
  GET_MARKET_SHARE_ERROR: 'GET_MARKET_SHARE_ERROR',

  GET_INNOVATION_TYPE: 'GET_INNOVATION_TYPE',
  GET_INNOVATION_TYPE_RESET_TO_INITIAL: 'GET_INNOVATION_TYPE_RESET_TO_INITIAL',
  GET_INNOVATION_TYPE_RESOLVED: 'GET_INNOVATION_TYPE_RESOLVED',
  GET_INNOVATION_TYPE_ERROR: 'GET_INNOVATION_TYPE_ERROR',

  GET_LX_SUBTYPES: 'GET_LX_SUBTYPES',
  GET_LX_SUBTYPES_RESET_TO_INITIAL: 'GET_LX_SUBTYPES_RESET_TO_INITIAL',
  GET_LX_SUBTYPES_RESOLVED: 'GET_LX_SUBTYPES_RESOLVED',
  GET_LX_SUBTYPES_ERROR: 'GET_LX_SUBTYPES_ERROR',
  GET_LX_SUBTYPES_EMPTY: 'GET_LX_SUBTYPES_EMPTY',

  GET_INNOVATION_CHARACTERISTICS: 'GET_INNOVATION_CHARACTERISTICS',
  GET_INNOVATION_CHARACTERISTICS_RESET_TO_INITIAL: 'GET_INNOVATION_CHARACTERISTICS_RESET_TO_INITIAL',
  GET_INNOVATION_CHARACTERISTICS_RESOLVING: 'GET_INNOVATION_CHARACTERISTICS_RESOLVING',
  GET_INNOVATION_CHARACTERISTICS_RESOLVED: 'GET_INNOVATION_CHARACTERISTICS_RESOLVED',
  GET_INNOVATION_CHARACTERISTICS_ERROR: 'GET_INNOVATION_CHARACTERISTICS_ERROR',
  GET_INNOVATION_CHARACTERISTICS_EMPTY: 'GET_INNOVATION_CHARACTERISTICS_EMPTY',

  GET_ITEM_DETAILS: 'GET_ITEM_DETAILS',
  GET_ITEM_DETAILS_RESOLVING: 'GET_ITEM_DETAILS_RESOLVING',
  GET_ITEM_DETAILS_RESOLVED: 'GET_ITEM_DETAILS_RESOLVED',
  GET_ITEM_DETAILS_ERROR: 'GET_ITEM_DETAILS_ERROR',
  GET_ITEM_DETAILS_EMPTY: 'GET_ITEM_DETAILS_EMPTY',


  GET_ITEM_PICTURES: 'GET_ITEM_PICTURES',
  GET_ITEM_PICTURES_RESOLVING: 'GET_ITEM_PICTURES_RESOLVING',
  GET_ITEM_PICTURES_RESOLVED: 'GET_ITEM_PICTURES_RESOLVED',
  GET_ITEM_PICTURES_ERROR: 'GET_ITEM_PICTURES_ERROR',
  GET_ITEM_PICTURES_EMPTY: 'GET_ITEM_PICTURES_EMPTY',

  GET_ITEM_CHARACTERISTICS: 'GET_ITEM_CHARACTERISTICS',
  GET_ITEM_CHARACTERISTICS_RESOLVED: 'GET_ITEM_CHARACTERISTICS_RESOLVED',
  GET_ITEM_CHARACTERISTICS_ERROR: 'GET_ITEM_CHARACTERISTICS_ERROR',
  GET_ITEM_CHARACTERISTICS_EMPTY: 'GET_ITEM_CHARACTERISTICS_EMPTY',

  // reducer actions
  SET_PROFILER_CONTEXT: 'SET_PROFILER_CONTEXT',

  // update and create context information
  UPSERT_PROFILER_CONTEXT: 'UPSERT_PROFILER_CONTEXT',
  UPSERT_PROFILER_CONTEXT_RESOLVING: 'UPSERT_PROFILER_CONTEXT_RESOLVING',
  UPSERT_PROFILER_CONTEXT_RESOLVED: 'UPSERT_PROFILER_CONTEXT_RESOLVED',
  UPSERT_PROFILER_CONTEXT_ERROR: 'UPSERT_PROFILER_CONTEXT_ERROR',

  // clear store
  CLEAR_STORE: 'CLEAR_STORE',

  SET_CONTEXT_ID: 'SET_CONTEXT_ID',
};
