export const DASHBOARD_ACTIONS = {
  FETCH_DATASETS: 'FETCH_DATASETS',
  FETCH_DATASETS_RESOLVING: 'FETCH_DATASETS_RESOLVING',
  FETCH_DATASETS_RESOLVED: 'FETCH_DATASETS_RESOLVED',
  FETCH_DATASETS_ERROR: 'FETCH_DATASETS_ERROR',

  FETCH_USER_PREFERENCE: 'FETCH_USER_PREFERENCE',
  FETCH_USER_PREFERENCE_RESOLVING: 'FETCH_USER_PREFERENCE_RESOLVING',
  FETCH_USER_PREFERENCE_RESOLVED: 'FETCH_USER_PREFERENCE_RESOLVED',
  FETCH_USER_PREFERENCE_ERROR: 'FETCH_USER_PREFERENCE_ERROR',

  SAVE_USER_PREFERENCE: 'SAVE_USER_PREFERENCE',
  SAVE_USER_PREFERENCE_RESOLVED: 'SAVE_USER_PREFERENCE_RESOLVED',
  SAVE_USER_PREFERENCE_ERROR: 'SAVE_USER_PREFERENCE_ERROR'

};
